import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OD2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={(inter.className, "bg-bg_color")}>
        <div className="header flex" id="header">
          <Image
            src="/odd.png"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className="m-8 ml-0 w-60 h-37 flex-auto border-10 bg-card_bg_color rounded  content-center text-center ">
            {" "}
            Nav Bar
          </div>
        </div>

        {children}

        <div className=" h-20 fixed bottom-0 left-0 flex w-full items-end justify-center bg-black">
          <div className="flex-auto w-30 ">
          </div>
          <div className="flex-auto w-40content-between justify-items-center">
              <Image
                src="/odd.png"
                alt="OD2 Logo"
                className="-mt-9 bg-black mx-auto border-white border-2 rounded-lg"
                width={100}
                height={100}
                priority
              />
            <h3 className="text-center outline-text_color pt-3">ONE DAY DEVELOPERS</h3>
          </div>
          <div className="flex-auto w-30">
            <h3>custom part</h3>
          </div>
        </div>
        
      </body>
    </html>
  );
}
