export const metadata = {
  title: "About Us",
  description: "Learn about One Day Developers (OD2), a team of experts delivering exceptional software solutions, Android apps, and desktop applications, all within 24 hours.",
  openGraph: {
    title: "About Us | OD2",
    description: "Learn about One Day Developers (OD2), a team of experts delivering exceptional software solutions, Android apps, and desktop applications, all within 24 hours.",
  },
  keywords: [
    "One Day Developers",
    "OD2",
    "software development",
    "Android development",
    "desktop applications",
    "integration services",
    "24-hour project delivery",
    "rapid development",
    "rapid innovation",
    "rapid project delivery",
    "OD2.in",
    "Free Image to Blob Converter",
    "OD2 Image to Blob Converter",
    "Free temp mail",
    "OD2 temp mail",
    "Free temporary email",
    "OD2 temporary email",
    "Free disposable email",
    "OD2 disposable email",
    "Free throwaway email",
    "OD2 throwaway email",
    "Free fake email",
    "OD2 fake email",
    "Free email generator",
    "OD2 email generator",
    "Free email service",
    "OD2 email service",
    "Free email provider",
    "OD2 email provider",
    "Free email address",
    "OD2 email address",
    "Free email account",
    "OD2 email account",
    "Free email inbox",
    "OD2 email inbox",
    "Free email domain",
    "OD2 email domain",
    "Free email hosting",
    "OD2 email hosting",
    "Free email forwarding",
    "OD2 email forwarding",
    "Free email alias",
    "OD2 email alias",
    "Free email service provider",
    "OD2 email service provider",
  ],
};
  
export default function AboutLayout({ children }) {
  return <>{children}</>;
}
