import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OD2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <div className="w-full">{children}</div>;
}
