export const metadata = {
    title: "OD2 Billing System - Advanced & Customizable Billing Solutions",
    description: "OD2 Billing System offers a flexible, secure, and advanced billing platform built on Next.js and Tailwind CSS for multi-platform support, customizable workflows, and high-performance database management.",
    openGraph: {
      title: "OD2 Billing System - Advanced & Customizable Billing Solutions",
      description: "OD2 Billing System offers a flexible, secure, and advanced billing platform built on Next.js and Tailwind CSS for multi-platform support, customizable workflows, and high-performance database management.",
    },
    keywords: [
      "OD2 billing system",
      "OD2 billing software",
      "OD2 billing platform",
      "OD2 billing tool",
      "OD2 billing service",
      "OD2 billing solution",
      "OD2 billing app",
      "OD2 billing website",
      "OD2 billing company",
      "OD2 billing management",
      "OD2 billing database",
      "OD2 billing automation",
      "OD2 billing integration",
      "OD2 billing customization",
      "OD2 billing workflow",
      "OD2 billing process",
      "OD2 billing system online",
      "OD2 billing software online",
      "OD2 billing platform online",
      "OD2 billing tool online",
      "OD2 billing service online",
      "OD2 billing solution online",
      "OD2 billing app online",
      "OD2 billing website online",
      "OD2 billing company online",
      "OD2 billing management online",
      "OD2 billing database online",
      "OD2 billing automation online",
      "OD2 billing integration online",
      "OD2 billing customization online",
      "OD2 billing workflow online",
      "OD2 billing process online",
      "OD2 billing system software",
      "OD2 billing system platform",
      "OD2 billing system tool",
      "OD2 billing system service",
      "OD2 billing system solution",
      "OD2 billing system app",
      "OD2 billing system website",
      "OD2 billing system company",
      "OD2 billing system management",
      "OD2 billing system database",
      "OD2 billing system automation",
      "OD2 billing system integration",
      "OD2 billing system customization",
      "OD2 billing system workflow",
      "OD2 billing system process",
      "OD2 billing system software online",
      "OD2 billing system platform online",
      "OD2 billing system tool online",
      "OD2 billing system service online",
      "OD2 billing system solution online",
      "OD2 billing system app online",
      "OD2 billing system website online",
      "OD2 billing system company online",
      "OD2 billing system management online",
      "OD2 billing system database online",
      "OD2 billing system automation online",
      "OD2 billing system integration online",
      "OD2 billing system customization online",
      "OD2 billing system workflow online",
      "OD2 billing system process online",
      "OD2 billing system software online",
      "OD2 billing system platform online",
      "OD2 billing system tool online",
      "OD2 billing system service online",
      "OD2 billing system solution online",
      "OD2 billing system app online In Madurai",
      "Madurai billing system",
      "OD2 billing system Madurai",
      "OD2 billing software Madurai",
      "Lowest price billing system",
      "Best billing system",
      "Top billing system",
      "Quality billing system"],
  };
  
  export default function BillingSystem({ children }) {
    return <>{children}</>;
  }
  