export const metadata = {
    title: "Passport Size Printable",
    description: "Get your passport-size photo perfectly resized and ready for print on 6x4 or 4x6 paper. Quick, easy, and high-quality images for all your official document needs.",
    openGraph: {
      title: "Passporr Size Printable",
      description: "Get your passport-size photo perfectly resized and ready for print on 6x4 or 4x6 paper. Quick, easy, and high-quality images for all your official document needs.",
    },
    keywords: [
      "passport size photo",
      "passport photo print",
      "passport photo print online",
      "passport photo print near me",
      "passport photo print 4x6",
      "passport photo print 6x4",
      "passport photo print size",
      "passport photo print service",
      "passport photo print shop",
      "passport photo print cost",
      "passport photo print price",
      "passport photo print app",
      "passport photo print software",
      "passport photo print online free",
      "passport photo print online india",
      "passport photo print online uk",
      "passport photo print online canada",
      "passport photo print online australia",
      "passport photo print online singapore",
      "passport photo print online malaysia",
      "passport photo print online dubai",
      "passport photo print online usa",
      "passport photo print online europe",
      "passport photo print online worldwide",
      "passport photo print online delivery",
      "passport photo print online service",
      "passport photo print online review",
      "passport photo print online comparison",
      "passport photo print online best",
      "passport photo print online top",
      "passport photo print online quality",
      "passport photo print online fast",
      "passport photo print online cheap",
      "passport photo print online affordable",
      "passport photo print online reliable",
      "passport photo print online accurate",
      "passport photo print online easy",
      "passport photo print online quick",
      "passport photo print online simple",
      "passport photo print online user-friendly",
      "passport photo print online secure",
      "passport photo print online private",
      "passport photo print online confidential",
      "passport photo print online safe",
      "passport photo print online trusted",
      "passport photo print online official",
      "passport photo print online professional",
      "passport photo print online business",
      "passport photo print online company",
      "passport photo print online website",
      "passport photo print online platform",
      "passport photo print online tool",
      "passport photo print online application",
      "passport photo print online software",
      "passport photo print online program",
      "passport photo print online system",
      "passport photo print online service",
      "passport photo print online solution",
      "passport photo print online method",
      "passport photo print online technique",
      "passport photo print online process",
      "passport photo print online step",
      "passport photo print online guide",
      "passport photo print online tutorial",
      "passport photo print online demo",
      "passport photo print online example",
      "passport photo print online sample",
      "Free Passport Size Printable",
      "OD2 Passport Size Printable",
      "OD2",
    ],
    };
  
  export default function PhotoLayout({ children }) {
    return <>{children}</>;
  }
  