import { Inter } from "next/font/google";
import "../styles/globals.css";
import Footer from "./components/footer";
import Header from "./components/header";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    template: "%s | OD2",
    default: "OD2",
  },
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      {/* Google Analytics using next/script */}
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-1CC0XPGF77"
        strategy="afterInteractive"
      />

      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-1CC0XPGF77');
        `}
      </Script>
      <body className={inter.className + "flex-col bg-white dark:bg-slate-800"}>
        <Header></Header>
        <div className="p-10">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
