export const metadata = {
  title: "Automated Workflow Designer | JSON-Based Visual Workflow Builder",
  description: "Create visual API workflows with OpenAPI integration. Build, export, and embed interactive workflow diagrams with our drag-and-drop interface. Perfect for API documentation and workflow visualization.",
  openGraph: {
    title: "Automated Workflow Designer | Visual API Workflow Builder",
    description: "Create visual API workflows with OpenAPI integration. Build, export, and embed interactive workflow diagrams with our drag-and-drop interface. Perfect for API documentation and workflow visualization.",
  },
  keywords: [
    "workflow builder",
    "visual workflow",
    "API workflow",
    "OpenAPI integration",
    "workflow designer",
    "API documentation",
    "visual API designer",
    "workflow visualization",
    "API flow chart",
    "automated workflow",
    "JSON workflow",
    "drag and drop workflow",
    "workflow export",
    "workflow import",
    "iframe embeddable",
    "workflow documentation",
    "API flow diagram",
    "visual programming",
    "no-code workflow",
    "REST API workflow",
    "workflow canvas",
    "API workflow tool",
    "API testing",
    "Postman collection",
    "cURL examples",
    "API workflow automation",
    "microservices API",
    "RESTful services",
    "API security",
    "CORS handling",
    "API monitoring",
    "API performance",
    "OpenAPI specification",
    "Swagger documentation",
    "GraphQL API",
    "real-time API",
    "batch processing API",
    "file upload API",
    "data synchronization",
    "API middleware",
    "request validation",
    "response formatting",
    "API logging",
    "debug API calls",
    "API status codes",
    "pagination API",
    "filtering API",
    "sorting API",
    "search API",
    "bulk operations API",
  ],
};
  
export default function AWDLayout({ children }) {
  return <>{children}</>;
}
